site_name: Documentation for inseri core <sup>beta</sub>
site_url: https://docs.inseri.swiss/
repo_url: https://github.com/inseri-swiss/inseri-core-wp
nav:
  - "inseri.swiss": https://inseri.swiss/
  - "About": "index.md"
  - "getting-started.md"
  - "Tutorials":
    - "tutorials/hello-world.md"
    - "tutorials/data-mapping-with-python.md"
  - "Blocks":
    - "blocks/download.md"
    - "blocks/dropdown.md"
    - "blocks/html.md"
    - "blocks/image.md"
    - "blocks/localFileImport.md"
    - "blocks/mediaCollection.md"
    - "blocks/plotly.md"
    - "blocks/python.md"
    - "blocks/textEditor.md"
    - "blocks/textViewer.md"
    - "blocks/webApi.md"
    - "blocks/zenodo.md"
  - "How to":
    - "how-to/visualizations.md"
    - "how-to/workWithFiles.md"
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
  palette:
    primary: white
    accent: yellow
  logo: assets/inseri_logo.svg
  favicon: assets/inseri_logo.svg
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: material/home
      link: https://inseri.swiss/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - mkdocs_graphviz:
      color: 4051b5
  - md_in_html
  - attr_list


plugins:
  - glightbox
  - search
