site_name: Documentation for inseri core <sup>beta</sub>
site_url: https://docs.inseri.swiss/
repo_url: https://github.com/inseri-swiss/inseri-core-wp
nav:
  - 'Home': 'index.md'
  - 'getting_started.md'
  - 'Tutorials':
      - 'tutorials/hello_world.md'
      - 'tutorials/data_mapping_with_python.md'
  - 'Blocks':
      - 'blocks/overview.md'
      - 'blocks/cytoscape.md'
      - 'blocks/dataTable.md'
      - 'blocks/download.md'
      - 'blocks/dropdown.md'
      - 'blocks/export.md'
      - 'blocks/html.md'
      - 'blocks/iiifViewer.md'
      - 'blocks/image.md'
      - 'blocks/javascript.md'
      - 'blocks/localFileImport.md'
      - 'blocks/mediaCollection.md'
      - 'blocks/plotly.md'
      - 'blocks/python.md'
      - 'blocks/slider.md'
      - 'blocks/textEditor.md'
      - 'blocks/textViewer.md'
      - 'blocks/webApi.md'
      - 'blocks/zenodo.md'
  - 'Features':
      - 'features/sidebar.md'
      - 'features/hide_invisible_blocks.md'
      - 'features/data_flow.md'
      - 'features/block_duplication.md'
  - 'How to':
      - 'how-to/playground.md'
      - 'how-to/visualizations.md'
      - 'how-to/work_with_files.md'
      - 'how-to/python_packages.md'
  - 'inseri.swiss ↗': https://inseri.swiss/

theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

  palette:
    primary: black
    accent: yellow
  logo: assets/inseri_logo.svg
  favicon: assets/inseri_logo.svg
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: material/home
      link: https://docs.inseri.swiss/
    - icon: material/arrow-top-right
      link: https://inseri.swiss/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - mkdocs_graphviz:
      color: 4051b5
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - glightbox
  - search
  - redirects:
      redirect_maps:
        'how-to/packages.md': 'how-to/python_packages.md'
        'how-to/workWithFiles.md': 'how-to/work_with_files.md'
        'features/dataflow.md': 'features/data_flow.md'
        'features/dataFlow.md': 'features/data_flow.md'
        'features/DataFlow.md': 'features/data_flow.md'
        'features/hideInvisibleBlocks.md': 'features/hide_invisible_blocks.md'
        'features/blockDuplication.md': 'features/block_duplication.md'
        'tutorials/data-mapping-with-python.md': 'tutorials/data_mapping_with_python.md'
        'tutorials/hello-world.md': 'tutorials/hello_world.md'
        'getting-started.md': 'getting_started.md'
