<?php

function inseri_core_make_readme($post_id, $blueprint) {
	?>
# README

Original WordPress Post / Page: <?php echo get_permalink($post_id); ?>

This readme.md file was generated by the Export Block of the [inseri core plugin](https://wordpress.org/plugins/inseri-core/) on <?php echo date('Y-m-d H:i:s'); ?> UTC. It is intended to make the content of the original post open access by providing the details needed to replicate it.

**Warning**: The Media Library content is not supported. It has all the limitations of the WXR file used to export a post.

To replicate the original post, please consider:

- `blueprint.json` (see https://wordpress.github.io/wordpress-playground/blueprints-api/index) to inspect the version of the PHP, WordPress, plugins, and theme
- `post.xml` which is the WXR file (some instructions are available directly in the first lines of the file)

It is expected that you can replicate the content using [WordPress Playground](https://wordpress.github.io/wordpress-playground/):

1. Open the following link:
```
https://playground.wordpress.net/#<?php echo $blueprint; ?>

```
2. Go to the admin panel -> Tools -> Import -> WordPress -> Run Importer and upload the `post.xml` file
    <?php
}
