openapi: 3.0.0
info:
  title: inseri core API
  version: 1.0.0

servers:
  - url: http://localhost/?rest_route=/

paths:
  /inseri/v1/datasources:
    get:
      tags:
        - datasources
      summary: Retrieve all datasources
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Datasource'
    post:
      tags:
        - datasources
      summary: Create new datasource
      description: It requires the capability 'publish_posts'. (User with role 'Author')
      requestBody:
        description: Leave the id empty
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Datasource'
        required: true
      parameters:
        - name: X-WP-Nonce
          description: WP authentication token
          in: header
          schema:
            type: string
          required: true
      responses:
        '201':
          description: datasource created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datasource'
        '400':
          description: missing required field
  /inseri/v1/datasources/{id}:
    get:
      tags:
        - datasources
      summary: Retrieve a specific datasource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datasource'
        '404':
          description: not found
    put:
      tags:
        - datasources
      summary: Update a specific datasource
      description: If the owner of datasource makes a request, the capability 'publish_posts' is required. (User with role 'Author') Otherwise the capability 'edit_others_posts' is required. (User with role 'Editor')
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: X-WP-Nonce
          description: WP authentication token
          in: header
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Datasource'
        required: true
      responses:
        '200':
          description: successfully updated
        '400':
          description: missing required field
        '404':
          description: not found
    delete:
      tags:
        - datasources
      summary: Delete a datasource
      description: If the owner of datasource makes a request, the capability 'delete_posts' is required. (User with role 'Author') Otherwise the capability 'delete_others_posts' is required. (User with role 'Editor')
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: X-WP-Nonce
          description: WP authentication token
          in: header
          schema:
            type: string
          required: true
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datasource'
        '404':
          description: not found

components:
  schemas:
    Datasource:
      type: object
      required:
        - id
        - description
        - type
        - method
        - url
      properties:
        id:
          type: integer
          example: 10
        description:
          type: string
          example: Foo Library
        type:
          type: string
          example: 'rest'
        author:
          type: integer
          example: 5
        author_name:
          type: string
          example: admin
        method:
          type: string
          example: POST
        url:
          type: string
          example: 'http://www.inseri.swiss'
        headers:
          type: object
          example: '{content-type: application/json}'
        query_params:
          type: object
          example: '{page_size: 10}'
        body:
          type: string
          example: '{}'
