name: 'deploy to WP'

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      push-tag:
        type: boolean
        required: true
        default: false
      push-trunk:
        type: boolean
        required: true
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}

      - name: Download plugin
        uses: actions/download-artifact@v3
        with:
          name: ready-zip

      - name: Extract Archive
        run: |
          mkdir zip-content
          unzip inseri-core.zip -d zip-content
          ls -lA zip-content

      - name: Checkout from WordPress.org
        run: |
          svn co http://svn.wp-plugins.org/inseri-core wp/inseri-core

      - name: Sync code changes to tag
        if: ${{inputs.push-tag}}
        run: |
          rm -rf wp/inseri-core/tags/${{ inputs.version }}/*
          mkdir -p wp/inseri-core/tags/${{ inputs.version }}
          cp -a zip-content/* wp/inseri-core/tags/${{ inputs.version }}
          ls -lA wp/inseri-core/tags/${{ inputs.version }}

      - name: Sync code changes to trunk
        if: ${{inputs.push-trunk}}
        run: |
          rm -rf wp/inseri-core/trunk/*
          cp -a zip-content/* wp/inseri-core/trunk/
          ls -lA wp/inseri-core/trunk/

      - name: Sync asset changes
        run: |
          if [ -d .wordpress-org/ ]; then
            rm -rf wp/inseri-core/assets/*
            cp -a .wordpress-org/* wp/inseri-core/assets/
            ls -lA wp/inseri-core/assets/
          fi

      - name: Deploy to WordPress.org
        run: |
          cd wp/inseri-core
          svn add * --force
          svn ci --no-auth-cache --username ${{ secrets.WP_USERNAME }} --password="${{ secrets.WP_PASSWORD }}" -m "Deploy ${{ inputs.version }} version"
