name: docs
on:
  push:
    branches:
      - feat/add-mkdocs
jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install mkdocs
      - run: mkdocs gh-deploy --force --clean --verbose
