name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run plugin-zip

      - uses: actions/upload-artifact@v4
        with:
          name: ready-zip
          path: inseri-core.zip
          retention-days: 14

      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: inseri-core.zip

  deploy:
    name: Deploy to WordPress.org
    needs: release
    uses: ./.github/workflows/deploy-wp.yml
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
      push-tag: true
      push-trunk: true
